name = "lean-redis"
version = "0.1.0"
defaultTargets = ["lean-redis"]

[[lean_lib]]
name = "LeanRedis"

[[lean_lib]]
name = "LeanRedisTest"
globs = ["Test.+"]

[[lean_exe]]
name = "lean-redis-cli"
root = "Cli"
